### ISSUE TITLE
你好，npm install之后使用npm run server时出现如下bug

### ISSUE THREAD

**Issue by Song-XiaoPeng** [whxaxes/canvas-test#10]
$ npm run server

> test@0.1.0 server D:\vue\canvas-test
> node app.js

D:\vue\canvas-test\app.js:7
router.init({debug : true}).setMap('**/*' , '**/*').listen(port);
       ^

TypeError: router.init is not a function
    at Object.<anonymous> (D:\vue\canvas-test\app.js:7:8)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 server: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional log               ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-03-09T0               7_00_55_319Z-debug.log

**Comment by whxaxes** [comment]
已 fixed
